export const MoviesData = [
    {id: "M0001", title: "Avengers Endgame", img: "./assets/img/avengers-endgame.jpg", description: "With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.After the devastating events of Avengers: Infinity War (2018), the universe is in ruins.", release: 2012},
    {id: "M0002", title: "The Flash", img: "./assets/img/flash.jpg", description: "The series follows Barry Allen, portrayed by Grant Gustin, a crime scene investigator who gains super-human speed, which he uses to fight criminals, including others who have also gained superhuman abilities.", release: 2005},
    {id: "M0003", title: "Hawkeye", img: "./assets/img/hawkeye.jpg", description: "Series based on the Marvel Comics superhero Hawkeye, centering on the adventures of Young Avenger, Kate Bishop, who took on the role after the original Avenger, Clint Barton. Former Avenger Clint Barton has a seemingly simple mission: get back to his family for Christmas.", release: 2023},
    {id: "M0004", title: "Inception", img: "./assets/img/inception.jpg", description: "Inception is a 2010 science fiction action film written and directed by Christopher Nolan, who also produced the film with Emma Thomas, his wife. The film stars Leonardo DiCaprio as a professional thief who steals information by infiltrating the subconscious of his targets. He is offered a chance to have his criminal history erased as payment for the implantation of another person's idea into a target's subconscious.", release: 2015},
    {id: "M0005", title: "Iron Man 3", img: "./assets/img/iron-man-3.jpg", description: "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution. When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.", release: 2011},
    {id: "M0006", title: "Jurassic Park", img: "./assets/img/jurassic-park.jpg", description: "The story is about Jurassic Park, a nature reserve on a remote South American island owned by billionaire businessman John Hammond (Richard Attenborough). Hammond and his team of dedicated scientists have populated the park with genetically engineered dinosaurs.", release: 1999},
    {id: "M0007", title: "Mad Max", img: "./assets/img/mad-max.jpg", description: "The series follows the adventures of Rockatansky, a police officer in a future Australia which is experiencing societal collapse due to war and critical resource shortages. When his wife and child are murdered by a vicious biker gang, Max kills them in revenge and becomes a drifting loner in the Wasteland.", release: 2006},
    {id: "M0008", title: "Walle", img: "./assets/img/walle.jpg", description: "WALL•E (Waste Allocation Load Lifter Earth-Class) is the last robot left on Earth, programmed to clean up the planet, one trash cube at a time. However, after 700 years, he's developed one little glitch—a personality. He's extremely curious, highly inquisitive, and a little lonely.", release: 2019},
    {id: "M0009", title: "Star Trek Picard", img: "./assets/img/star-trek-picard.jpg", description: "Set at the end of the 24th century, 18 years after the events of Star Trek: Nemesis, with Sir Patrick Stewart reprising his iconic role, Star Trek: Picard revolves around retired admiral Jean-Luc Picard. He is still deeply affected by the loss of Lieutenant Commander Data, portrayed by Brent Spiner, and the destruction of Romulus, and steps into the next chapter of his life.", release: 2020}
]